### ISSUE TITLE
Duplicate columns on Patient List export 

### ISSUE THREAD

**Issue by olayemiibrahim** [uwrit/leaf#558] opened 2022-08-31 20:35 UTC
Hello everyone,

Is anyone else experiencing an issue with Leafs export? It looks like when we export patient information from the patient list tab all the columns are duplicated without their column headers. 

<img width="1456" alt="Screen Shot 2022-08-31 at 2 26 17 PM" src="https://user-images.githubusercontent.com/36490233/187775490-87b5031e-f3f1-486c-acc8-c9bd1a587629.png">

I had attempted to follow the export function in the [dataExport.ts](https://github.com/uwrit/leaf/blob/a65ed92953e4fcf7ee2222fc85f01b3798b45ca7/src/ui-client/src/actions/dataExport.ts) to see where the columns are being duplicated. It looks like the error would be in the getMultirowDatasetCSV function call on line 55, which leads to the [patientListWebWorker.ts](https://github.com/uwrit/leaf/blob/469d057078f12d9de0053345f6c073dd33b134aa/src/ui-client/src/providers/patientList/patientListWebWorker.ts) file. Going through the addMultiRowDataset function (assuming that is the correct one to look at) there doesn't seem to be any flaws in the logic. 

Has anyone seen this issue and been able to fix it?

**Comment by ndobb** [comment] 2022-09-09 17:28
Thanks for pointing this out, @olayemiibrahim . TLDR; the problem is in the [duplicate for loop in the WebWorkerContext.ts file](https://github.com/uwrit/leaf/blob/469d057078f12d9de0053345f6c073dd33b134aa/src/ui-client/src/providers/patientList/patientListWebWorkerContext.ts#L713).

### Background
Basically, web workers are odd. Especially when using `npm` and `webpack` compilation and so on, things get wonky. You've probably noticed that everything under /ui-client/src/providers has both a `*WebWorker.ts` file and a `*WebWorkerContext.ts` file.

The `*WebWorker.ts workerContext()` function is written in TypeScript, but not actually used in the app.

Why? Well, writing it in TypeScript allows us to get type checking and helpful stuff like that. However due to oddities of how the browser initializes webworkers (specifically, [you just send a blob string of code](https://github.com/uwrit/leaf/blob/469d057078f12d9de0053345f6c073dd33b134aa/src/ui-client/src/providers/patientList/patientListWebWorker.ts#L105), basically that won't work. This causes all sorts of headaches. I've seen quite a few workarounds in the past (and maybe there are better, more recent, solutions), but to my knowledge really do a great, reliable job of making this easier.

Anyway, I've never advocated the way we do this with Leaf as ideal or the best solution (clearly, given this issue and possible others, it's not), but I convert the TypeScript `workerContext()` function into a big string, then plop that in the `*WebWorkerContext.ts` file. That's [what is actually run in the webworker](https://github.com/uwrit/leaf/blob/469d057078f12d9de0053345f6c073dd33b134aa/src/ui-client/src/providers/patientList/patientListWebWorker.ts#L100).

If you look at the line linked above, you can see that the `for loop` gets unnecessarily repeated, but only in the `*WebWorkerContext.ts` file. It must have been a copy/paste error or something I missed.

I'll make a fix for this of course, but in the meantime, if necessary, you can just manually cut out [those 4 unnecessary lines of the `for loop`](https://github.com/uwrit/leaf/blob/469d057078f12d9de0053345f6c073dd33b134aa/src/ui-client/src/providers/patientList/patientListWebWorkerContext.ts#L713), then recompile and redeploy. That should fix it.

**Comment by ndobb** [comment] 2023-04-24 23:50
Fixed in [3.11.3](https://github.com/uwrit/leaf/releases/tag/v3.11.3)

**Closed** 2023-04-24 23:49 UTC
